### ISSUE TITLE
Autodiff to require C++17?

### ISSUE THREAD

**Issue by pulver** [pulver/autodiff#19]
Hi @kedarbhat,

In the `dev-atan2` branch I just commited an update to [`apply_coefficients_with_horner()`](https://github.com/pulver/autodiff/blob/4e9d8466e8b99291e087fb2a10b4547749b1c59c/include/boost/math/differentiation/autodiff.hpp#L1551) that includes the use of lambdas that accept a parameter pack. This is [called](https://github.com/pulver/autodiff/blob/4e9d8466e8b99291e087fb2a10b4547749b1c59c/include/boost/math/differentiation/autodiff.hpp#L1529) by `atan2()`. In the case of `atan2()`, there are 2 independent variables but I wanted to use this opportunity to motivate a helper function `apply_coefficients_with_horner()` that generalizes to any number of independent variables. This seems to be most efficiently written with lambdas that accept `auto...` parameters.

Do you see a reasonable way to implement this in C++11 with MSVC14 compatibility?

I've added `example/atan2.cpp` to test it with, along with updating `test/test_autodiff5.cpp`.

**Comment by kedarbhat** [comment]
Since generic/variadic lambdas are involved, there are a few things that might work; GCC has an extension for template lambdas (different syntax than normal generic lambdas), but I doubt this would be portable. A function object would be the most straightforward way to do this, I think.

**Comment by pulver** [comment]
> A function object would be the most straightforward way to do this, I think.

Good idea, I'll try that.

**Comment by pulver** [comment]
I've created a [Curry](https://github.com/pulver/autodiff/blob/d658a48f6249eed5cebe0d0b93953bf579a11b28/include/boost/math/differentiation/autodiff_cpp11.hpp#L98) template class for the C++11 version to mimic the `[&](auto... indices){}` variadic lambda in the C++17 version. This is getting close, but gives a linker error when compiling in C++11:

    g++ -std=c++11 -Iinclude -I$HOME/src/boost_1_70_0 example/atan2.cpp

    undefined reference to `boost::math::differentiation::autodiff_v1::detail::fvar<double, 5ul>::order_sum'

This looks similar to issues around odr-use of the `static constexpr size_t order_sum` member as discussed [here](https://stackoverflow.com/questions/53407371/undefined-reference-to-class-static-constexpr-struct-g-vs-clang) for instance. (Though it's possible it's a different diagnosis altogether.) I was wondering if you would be able to take a shot at supporting this in C++11? The C++17 version works fine. The Curry class isn't needed, if you see a better way around it. The goal would just be to support the functionality of the `apply_coefficients` template functions in C++11 from the `dev-atan2` branch without having to downgrade the C++17 version.

**Comment by kedarbhat** [comment]
I’ll take a look in a little bit.

**Comment by pulver** [comment]
Thank you. I'd like to better understand why this is happening for C++11. In the meantime, I added a conditional preprocessor check in [apply_coefficients](https://github.com/pulver/autodiff/blob/4f9be29c1990784b698233ca270807a638251aa5/include/boost/math/differentiation/autodiff.hpp#L997) to emphasize that this is a hack:
```
#ifndef BOOST_NO_CXX17_IF_CONSTEXPR
    size_t i = std::min(order, order_sum);
#else
    size_t i = std::min(order, get_order_sum<fvar<RealType,Order>>::value);
#endif
```

**Comment by kedarbhat** [comment]
I'm using [Definitions and ODR](https://en.cppreference.com/w/cpp/language/definition) as my reference. I also found a similar problem on [stackoverflow.com](https://stackoverflow.com/questions/34638149/static-constexpr-members-seem-not-to-go-along-with-stdmin).

Taking the code back to commit d658a48f6249eed5cebe0d0b93953bf579a11b28). Here are some observations about the issue which finally manifested:

We're missing namespace scope declarations of `order_sum` and `depth`**. This should have broken other parts of the code, and we've never had namespace scope declarations of those variables, so this doesn't entirely make sense of the issue, but it does "fix" the code if the declarations are added at namespace scope as below:
```
template<typename RealType, std::size_t Order>
constexpr std::size_t fvar<RealType, Order>::depth;
template<typename RealType, std::size_t Order>
constexpr std::size_t fvar<RealType, Order>::order_sum;
```

In C++17, the requirement for a namespace scope definition of a `static constexpr` data member is deprecated, which is why you were able to build in C++17 without issue, but C++11/C++14 both failed.

Not understanding why this hasn't been an issue previously, I see that the only uses of `order_sum` that are ODR-used are those uses wherein `order_sum` is passed into `std::min`. 
```size_t i = std::min(order, order_sum);```

Since `std::min` accepts it arguments as references, we need namespace scope declarations if we're going to pass in `order_sum` as an argument. 

Changing the `std::min` lines (causing ODR-usage) to ```size_t i = order <= order_sum ? order : order_sum;```, the problem disappears. 

I'll send a PR shortly, but to maintain portability and to avoid cluttering the code unnecessarily, we can use aliases to `std::integral_constant` for `depth`/`order_sum`, and will need to add `::value` to access the static constant within `std::integral_constant`.  The point of this is to keep the code as standard-agnostic as possible.

**Comment by pulver** [comment]
> to maintain portability and to avoid cluttering the code unnecessarily, we can use aliases to std::integral_constant for depth/order_sum, and will need to add ::value to access the static constant within std::integral_constant. The point of this is to keep the code as standard-agnostic as possible.

Generally speaking, I really don't want to sacrifice new C++ language features for backward compatibility. This is the whole reason for a separate autodiff_cpp11.hpp file.

This change seems to me to be a downgrade of the C++17 version. I would really like to keep `order_sum` as either a constexpr variable or method. I would much rather keep the version with:
```
#ifndef BOOST_NO_CXX17_IF_CONSTEXPR
    size_t i = std::min(order, order_sum);
#else
    size_t i = std::min(order, get_order_sum<fvar<RealType,Order>>::value);
#endif
```
to make it clear that there is compiler-versioning issue here.

In any case, thank you for looking into this and bringing clarity to this issue.

**Comment by pulver** [comment]
Actually thanks to your research this code makes the issue more clear 7818e27b
```
#ifndef BOOST_NO_CXX17_IF_CONSTEXPR
    size_t i = std::min(order, order_sum);
#else
    size_t i = order < order_sum ? order : order_sum;
#endif
```
